server:
  address: :9526
  #两种模式:release、debug
  model: debug

db:
  dialects: mysql
  host: localhost
  port: 3306
  db: go_blog
  username: root
  password: 123123
  charset: utf8
  maxIdle: 10
  maxOpen: 100

myLog:
  path: ./log
  name: sys
  #控制台console 文件file（生产）
  model: file

cache:
  expire: 7200
  clearup: 600
